language: node_js
node_js:
- '4.2'
env:
  - CXX=g++-4.8
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - g++-4.8
    - google-chrome-stable
  firefox: latest
before_install:
- npm install grunt-cli -g
- firefox --version 2>/dev/null
- google-chrome --product-version
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- grunt
- test -z "$(git status -s)"
notifications:
	webhooks: https://slack-docker-hub-integration.herokuapp.com/services/T03DHTPR2/B03M17530/pZdZz88ZDn5aaqwPkbrM8WmE


